# mini-coreutils - A minimal set of core utilities for Unix-like systems
# Copyright (C) 2025 Qiu Yixiang
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Config Makefile

# Toolchain prefix
TOOL_CHAIN_PREFIX := 
CC   :=   $(TOOL_CHAIN_PREFIX)gcc
CXX  :=   $(TOOL_CHAIN_PREFIX)g++

# 0: release mode, 1: debug mode
DEBUG_MODE := 0 

# 0: not use for kernel, 1: use for kernel
KERNEL_MODE := 0
